### ISSUE TITLE
Error: No files in the deployment

### ISSUE THREAD

**Issue by zrrrzzt** [sergiodxa/now-storage#1]
I get an error when I try to use this module.

This code

```JavaScript
const { upload } = require('now-storage')
const file = {name: 'testfile.txt', content: 'This is my test.... believe it!'}
const STORAGE_TOKEN = 'my-now-token'

async function uploadFile () {
  try {
    const { url } = await upload(STORAGE_TOKEN, {
      name: 'my-file.txt',
      content: 'This is a file uploaded with now-storage.'
    })
    console.log(url)
  } catch (error) {
    console.error(error)
  }
}

uploadFile()
```

Returns this error

```sh
Error: No files in the deployment
    at retry (/node_modules/now-storage/index.js:88:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: There was an error while deploying.
    at upload (node_modules/now-storage/index.js:96:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by sergiodxa** [comment]
Fixed in the version 1.0.1
